### ISSUE TITLE
Add default quote configuration?

### ISSUE THREAD

**Issue by xianghongai** [alanmbarr/vscode-quotify#4]
Can be set to single or double quotes.

This extension helped me a lot, Thanks a bunch!

**Comment by alanmbarr** [comment]
Makes sense if you have a preference you might suggest a design. Otherwise i'll have to think how this might look as I have time. Thanks for the feedback!

**Comment by alanmbarr** [comment]
@xianghongai sorry for the long answer. This was added in version 0.0.4 in a pull ask that enables you to set single or double quotes.
